/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TvShowsRouteImport } from './routes/tv-shows'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as LanguageCodeRouteImport } from './routes/language.$code'
import { Route as GenreTypeIdRouteImport } from './routes/genre.$type.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsRoute = TvShowsRouteImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCodeRoute = LanguageCodeRouteImport.update({
  id: '/language/$code',
  path: '/language/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreTypeIdRoute = GenreTypeIdRouteImport.update({
  id: '/genre/$type/$id',
  path: '/genre/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/watchlist': typeof WatchlistRoute
  '/language/$code': typeof LanguageCodeRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/genre/$type/$id': typeof GenreTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/watchlist': typeof WatchlistRoute
  '/language/$code': typeof LanguageCodeRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/genre/$type/$id': typeof GenreTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/browse': typeof BrowseRoute
  '/category': typeof CategoryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv-shows': typeof TvShowsRoute
  '/watchlist': typeof WatchlistRoute
  '/language/$code': typeof LanguageCodeRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$id': typeof PersonIdRoute
  '/tv/$id': typeof TvIdRoute
  '/genre/$type/$id': typeof GenreTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/browse'
    | '/category'
    | '/movies'
    | '/search'
    | '/tv-shows'
    | '/watchlist'
    | '/language/$code'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/genre/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/browse'
    | '/category'
    | '/movies'
    | '/search'
    | '/tv-shows'
    | '/watchlist'
    | '/language/$code'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/genre/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/browse'
    | '/category'
    | '/movies'
    | '/search'
    | '/tv-shows'
    | '/watchlist'
    | '/language/$code'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/genre/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  BrowseRoute: typeof BrowseRoute
  CategoryRoute: typeof CategoryRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  TvShowsRoute: typeof TvShowsRoute
  WatchlistRoute: typeof WatchlistRoute
  LanguageCodeRoute: typeof LanguageCodeRoute
  MovieIdRoute: typeof MovieIdRoute
  PersonIdRoute: typeof PersonIdRoute
  TvIdRoute: typeof TvIdRoute
  GenreTypeIdRoute: typeof GenreTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language/$code': {
      id: '/language/$code'
      path: '/language/$code'
      fullPath: '/language/$code'
      preLoaderRoute: typeof LanguageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$type/$id': {
      id: '/genre/$type/$id'
      path: '/genre/$type/$id'
      fullPath: '/genre/$type/$id'
      preLoaderRoute: typeof GenreTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  BrowseRoute: BrowseRoute,
  CategoryRoute: CategoryRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  TvShowsRoute: TvShowsRoute,
  WatchlistRoute: WatchlistRoute,
  LanguageCodeRoute: LanguageCodeRoute,
  MovieIdRoute: MovieIdRoute,
  PersonIdRoute: PersonIdRoute,
  TvIdRoute: TvIdRoute,
  GenreTypeIdRoute: GenreTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
